---
- name: Testing andrewrothstein.cilium
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'cilium version'
      ansible.builtin.command: /usr/local/bin/cilium version
      changed_when: false
      register: cilium_test_output
    - name: Output of 'cilium version'
      ansible.builtin.debug:
        msg: '{{ cilium_test_output.stdout }}'
