---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/cilium version
      register: cilium_test_output
    - name: cilium version
      debug:
        msg: '{{ cilium_test_output.stdout }}'
